openapi: 3.0.1
info:
  title: prueba-tecnica
  description: Prueba técnica acceso
  version: 0.0.1-SNAPSHOT
  contact:
    name: Saturio Fernández Pachón
    url: https://github.com/satuFernandezKS/prueba-tecnica
    email: saturio.fernandez@kairosds.com
servers:
  - url: http://localhost:8080

paths:
  /prices/:
    get:
      tags:
        - Prices
      parameters:
        - name: applicationDate
          in: query
          schema:
            type: string
            format: date-time
            example: 2020-06-14T10:00:00
            required: true
        - name: productId
          in: query
          schema:
            type: number
            example: 35455
            required: true
        - name: brandId
          in: query
          schema:
            type: number
            example: 1
            required: true
      responses:
        200:
          description: Successful request with price
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Prices'
                  status:
                    type: number
                    example: 200
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

tags:
  - name: Prices

components:
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 200
              data:
                type: object
    400:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 400
              message:
                type: string
                example: ValidationError
    404:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: No se han encontrado resultados
    500:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 500
              message:
                type: string
                example: GenericServerError

  schemas:
    Prices:
      type: object
      properties:
        brandId:
          type: integer
          example: 1
        startDate:
          type: string
          format: date-time
          example: 2020-06-14T10:00:00
        endDate:
          type: string
          format: date-time
          example: 2020-06-14T10:00:00
        priceList:
          type: integer
          example: 2
        productId:
          type: integer
          example: 35455
        price:
          type: number
          example: 35,50
