DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES
(
    ID             IDENTITY NOT NULL AUTO_INCREMENT,
    BRAND_ID       INT,
    START_DATE     TIMESTAMP,
    END_DATE       TIMESTAMP,
    PRICE_LIST     INT,
    PRODUCT_ID     INT,
    PRIORITY       INT,
    PRICE          FLOAT,
    CURRENCY       VARCHAR,
    LAST_UPDATE    TIMESTAMP,
    LAST_UPDATE_BY VARCHAR
);